export const SELECT_MAP = 'SELECT_MAP'
// export const SELECT_YEAR = 'SELECT_YEAR'
export const SELECT_CITY = 'SELECT_CITY'
export const SELECT_STATE = 'SELECT_STATE'
// export const GET_MAP_DATA = 'GET_MAP_DATA'
