export const SELECT_MAP = 'SELECT_MAP'
export const SELECT_CITY = 'SELECT_CITY'
export const FILTER_STATE = 'FILTER_STATE'
export const SELECT_YEAR_OPTION = 'SELECT_YEAR_OPTION'
export const SELECT_STATE_OPTION = 'SELECT_STATE_OPTION'
export const CHANGE_MAP_SELECTOR = 'CHANGE_MAP_SELECTOR'

